[workspace]
members = [
  "protocol/rtmp",
  "protocol/httpflv",
  "protocol/hls",
  "library/bytesio",
  "application/xiu",
  "application/http-server",
  "application/pullrtmppushrtmp",
  "library/container/flv",
  "library/container/mpegts",
  "library/codec/h264",
  "library/logger",
]
