version: "3"
name: "restreamer"

# XIU test pod
services:

  # 1. Base streamer
  root_streamer:
    build:
      context: "."
      target: "runner"
      args:
        # BUILDER_TZ: ${BUILDER_TZ}
        TZ: ${TZ}
        PLATFORM: ${PLATFORM}
        VERSION: ${VERSION}
        APP_VERSION: ${APP_VERSION}
        PATH: ${PATH}
        APP_DIR: ${APP_DIR}
        BUILD_DIR: ${BUILD_DIR}
        USER: ${USER}
        UID: ${UID}
    image: "normkd/1688557675-test01:1.0.0"
    container_name: "${COMPOSE_PROJECT_NAME}.${ROOT}"
    environment:
      TZ: ${TZ}
      PATH: ${PATH}:${APP_DIR}
      SYSROOT: ${SYSROOT}
    working_dir: "/app"
    volumes:
      - "./ci/config:/app/config"
    user: "appuser"
    hostname: "streamer-00"
    expose:
      - "80"
      - "80/udp"
      - "443"
      - "1935"
      - "1935/udp"
      - "8000"
      - "8000/udp"
    networks:
      - intra
    #     ipv4_address: "172.16.100.5"
    # ports:
    #   - "55001:1935"
    #   - "1935:1935/udp"
    #   - "8000:8000" 
    #   - "8000:8000/udp"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    command: ["-c", "config/config_rtmp.toml"]

  # 2. Streamer instances
  streamer1:
    extends:
      service: "root_streamer"
    container_name: "${COMPOSE_PROJECT_NAME}.${NODE_01}"
    hostname: "streamer-01"
    # ports:
    #   - "55002:1935"
    #   - "8000:8000"
    # networks:
    #   intra:
    #     ipv4_address: "172.16.110.6"

  streamer2:
    extends:
      service: "root_streamer"
    container_name: "${COMPOSE_PROJECT_NAME}.${NODE_02}"
    hostname: "streamer-02"
    # ports:
    #   - "55003:1935"
    #   - "8000:8000"
    # networks:
    #   intra:
    #     ipv4_address: "172.16.120.5"

networks:
  intra:
    external: false
    attachable: false
    enable_ipv6: false
    name: "restreamer_pod"
    driver: "ipvlan"
    driver_opts:
      ipvlan_mode: "l2"
      ipvlan_flag: "bridge"
      subnet: "172.100.100.0/24"
      ip_range: "172.100.100.0/28"
      gateway: "172.100.100.10"
    # ipam:
    #   config:
    #     - subnet: "172.100.100.0/24"
    #     - ip_range: "172.100.100.0/28"
    #     - gateway: "172.100.100.10"
