[package]
name = "bytesio"
version = "0.3.2"
authors = ["HarlanC <wawacry@qq.com>"]
edition = "2018"
description = "a network io library using tokio."
license = "MIT"
repository = "https://github.com/harlanc/xiu"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.2"
bytes = "1.0.0"
rand = "0.3"
failure = "0.1.8"
tokio-util = { version = "0.6.5", features = ["codec"] }
futures = "0.3.5"
tokio-stream = { version = "0.1" }
log = "0.4"
async-trait = "0.1.70"

[dependencies.tokio]
version = "1.4.0"
default-features = false
#features = ["rt-core", "rt-threaded", "macros", "time","sync"]
features = ["full"]
