#live server configurations
##########################
#   RTMP configurations  #
##########################
[rtmp]
enabled = true
port = 1935
# pull streams from other server node.
[rtmp.pull]
enabled = false
address = "192.168.0.1"
port = 1935
# push streams to other server node.
[[rtmp.push]]
enabled = true
address = "localhost"
port = 1936
[[rtmp.push]]
enabled = true
address = "192.168.0.3"
port = 1935

##########################
# HTTPFLV configurations #
##########################
[httpflv]
enabled = true
port = 8081

##########################
#    HLS configurations  #
##########################
[hls]
enabled = true
port = 8080

##########################
#   LOG configurations   #
##########################
[log]
level = "info"
[log.file]
enabled = true
rotate = "minute" #day hour minute
path = "./logs"
