#live server configurations
##########################
#   RTMP configurations  #
##########################
[rtmp]
enabled = true
port = 1935
gop_num = 0
[rtmp.auth]
pull_enabled = true
push_enabled = true
# simple or md5
algorithm = "simple"
# pull streams from other server node.
[rtmp.pull]
enabled = false
address = "192.168.0.1"
port = 1935
# push streams to other server node.
[[rtmp.push]]
enabled = false
address = "localhost"
port = 1936
[[rtmp.push]]
enabled = false
address = "192.168.0.3"
port = 1935

[httpnotify]
enabled = true
on_publish = "http://localhost:3001/on_publish"
on_unpublish = "http://localhost:3001/on_unpuslish"
on_play = "http://localhost:3001/on_play"
on_stop = "http://localhost:3001/on_stop"

[authsecret]
# used for md5 authentication
key = ""
# used for simple authentication
password = ""


##########################
#    RTSP configurations  #
##########################
[rtsp]
enabled = false
port = 445
[rtsp.auth]
pull_enabled = true
push_enabled = true
# simple or md5
algorithm = "simple"

##########################
#    WebRTC configurations  #
##########################
[webrtc]
enabled = false
port = 8083
[webrtc.auth]
pull_enabled = true
push_enabled = true
# simple or md5
algorithm = "simple"

##########################
# HTTPFLV configurations #
##########################
[httpflv]
enabled = false
port = 8081
[httpflv.auth]
pull_enabled = true
# simple or md5
algorithm = "simple"


##########################
#    HLS configurations  #
##########################
[hls]
enabled = false
port = 8080
need_record = false
[hls.auth]
pull_enabled = true
# simple or md5
algorithm = "simple"


##########################
#   LOG configurations   #
##########################
[log]
level = "info"
[log.file]
# write log to file or not（Writing logs to file or console cannot be satisfied at the same time）.
enabled = false
rotate = "hour" #[day,hour,minute]
path = "./logs"
