[package]
name = "httpflv"
description = "httpflv library."
version = "0.4.1"
authors = ["HarlanC <wawacry@qq.com"]
repository = "https://github.com/harlanc/xiu"
license = "MIT"
readme = "README.md"
categories = ["multimedia", "multimedia::video", 'multimedia::audio']
keywords = ["httpflv", "video", "streaming"]
edition = "2018"

[dependencies]
byteorder = "1.4.2"
bytes = "1.0.0"
failure = "0.1.1"
log = "0.4"
axum = { version = "0.7.4" }
futures = "0.3"

streamhub = "0.2.0"
xflv = "0.4.0"
rtmp = "0.6.1"
commonlib = "0.1.0"

[dependencies.tokio]
version = "1.4.0"
default-features = false
features = ["full"]
