[package]
name = "pprtmp"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1.0"
log = "0.4.0"
env_logger = "0.10.0"
clap = "4.1.4"

rtmp = "0.5.0"
streamhub = "0.2.0"

[dependencies.tokio]
version = "1.26.0"
default-features = false
#features = ["rt-core", "rt-threaded", "macros", "time","sync"]
features = ["full"]
