[package]
name = "pprtmp"
version = "0.1.1"
edition = "2021"
description = "A pull push RTMP app"
authors = ["HarlanC <wawacry@qq.com"]
repository = "https://github.com/harlanc/xiu"
license = "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "^1.0"
log = "0.4.0"
env_logger = "0.10.0"
clap = "4.1.4"

rtmp = "0.6.2"
streamhub = "0.2.1"

[dependencies.tokio]
version = "1.26.0"
default-features = false
#features = ["rt-core", "rt-threaded", "macros", "time","sync"]
features = ["full"]
