[package]
name = "xflv"
description = "flv library."
version = "0.0.2"
authors = ["HarlanC <wawacry@qq.com"]
repository = "https://github.com/harlanc/xiu"
license = "MIT"
readme = "README.md"
categories = ["flv"]
keywords = ["flv", "video", "streaming"]
edition = "2018"

[dependencies]
byteorder = "1.4.2"
bytes = "1.0.0"
failure = "0.1.1"
bitvec = "0.20"
bytesio = "0.1.27"#{path = "../../bytesio/"}
log = "0.4"
